version: "3.8"

services:
  vic1:
    image: vulhub/wordpress:4.6
    container_name: vic1
    hostname: vic1
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    networks:
      victim:
        ipv4_address: 192.168.1.101
    volumes:
      - wp_vol:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: vic1_mysql
    hostname: vic1mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      victim:
        ipv4_address: 192.168.1.102

  
volumes:
  wp_vol: {}

networks:
  victim:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1